Repository prisma/quaint, pull requests merged in 2020-03, with the labels that each got.

#95 Ban Decimal::from_f64
  src/ast/values.rs
  src/connector/postgres/conversion.rs
Labels: process/next-milestone

#104 Set `max_idle_lifetime` to 5 minutes for now
  src/pooled.rs
Labels: kind/bug, kind/improvement

#107 Pool builder
  Cargo.toml
  src/connector/mysql.rs
  src/connector/postgres.rs
  src/connector/sqlite.rs
  src/lib.rs
  src/pooled.rs
  src/pooled/manager.rs
  src/visitor.rs
Labels: kind/improvement

#108 Make `Column` as `Aliasable`
  src/ast/column.rs
  src/ast/table.rs
Labels: kind/improvement

#109 Function should also be Aliasable
  src/ast/function.rs
Labels: kind/improvement

#111 Do not panic when system time is weird
  Cargo.toml
Labels: bug/2-confirmed

#112 Do not crash the whole system if no connection
  src/connector/postgres.rs
Labels: kind/bug
